/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nac.tbot2;

import com.google.gson.Gson;
import java.awt.EventQueue;
import java.awt.Rectangle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFrame;

/**
 *
 * @author nathaniel
 */
public class TBot2 extends javax.swing.JFrame {

    private BoardFrame boardFrame = new BoardFrame();
    private NextAreaFrame nextAreaFrame = new NextAreaFrame();
    private BoardWatcher boardWatcher = new BoardWatcher();
    private Gson gson = new Gson();
    private static final String SAVE_FILE = "save";
    private Preferences preferences = Preferences.userNodeForPackage(TBot2.class);

    /**
     * Creates new form TBot2
     */
    public TBot2() {
        initComponents();
        boardFrame.setBoardWatcher(boardWatcher);
        nextAreaFrame.setBoardWatcher(boardWatcher);
        boardWatcher.setBoardListener(new BoardListener() {
            @Override
            public void onPieceEntered() {
                System.out.println("onPieceEntered");
            }

            @Override
            public void onNextAreaChange(Integer[] aveColor) {
                System.out.println("onNextAreaChange" + aveColor);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Set Board");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Set Next Piece Area");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                boardFrame.setOpacity(0.5f);
                boardFrame.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                nextAreaFrame.setOpacity(0.5f);
                nextAreaFrame.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            preferences.putByteArray("nextAreaBounds", TBotUtils.serialize(boardWatcher.getNextAreaBounds()));
            preferences.putByteArray("bounds", TBotUtils.serialize(boardWatcher.getBounds()));
        } catch (Exception ex) {
            Logger.getLogger(TBot2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            byte[] d = preferences.getByteArray("nextAreaBounds", null);
            Rectangle rect = null;
            if (d != null) {
                rect = (Rectangle) TBotUtils.deserialize(d);
                if (rect != null) {
                    boardWatcher.setNextAreaBounds(rect);
                }
            }

            d = preferences.getByteArray("bounds", null);
            if (d != null) {
                rect = (Rectangle) TBotUtils.deserialize(d);
                if (rect != null) {
                    boardWatcher.setBounds(rect);
                }

            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TBot2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        JFrame.setDefaultLookAndFeelDecorated(true);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TBot2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
