/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TFrame.java
 *
 * Created on Mar 26, 2012, 6:27:58 PM
 */
package nac.tbot;

import java.awt.EventQueue;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author DTIT
 */
public class TFrame extends javax.swing.JFrame {

  private final Timer timer;
  private final BoardFrame boardFrame;
  private final BoardWatcher boardWatcher;

  /**
   * Creates new form TFrame
   */
  public TFrame() {
    initComponents();
    boardFrame = new BoardFrame();
    boardWatcher = new BoardWatcher();
    boardFrame.setBoardWatcher(boardWatcher);
    
    keyDelay.getDocument().addDocumentListener(new DocumentListener() {
      private void update(){
        try{
           boardWatcher.getKeyboard().setDelay(Integer.parseInt(keyDelay.getText()));
        }catch(Exception e){
          e.printStackTrace();
        }
      }
      @Override
      public void insertUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        update();
      }
    });
    
    towerGap.getDocument().addDocumentListener(new DocumentListener() {
      private void update(){
        try{
           boardWatcher.getBot().setTowerGap(Integer.parseInt(towerGap.getText()));
        }catch(Exception e){
          e.printStackTrace();
        }
      }
      @Override
      public void insertUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        update();
      }
    });
    
    buildUpLimit.getDocument().addDocumentListener(new DocumentListener() {
      private void update(){
        try{
           boardWatcher.getBot().setBuildUpLimit(Integer.parseInt(buildUpLimit.getText()));
        }catch(Exception e){
          e.printStackTrace();
        }
      }
      @Override
      public void insertUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        update();
      }
    });
    
    breakDownLimit.getDocument().addDocumentListener(new DocumentListener() {
      private void update(){
        try{
           boardWatcher.getBot().setBreakDownLimit(Integer.parseInt(breakDownLimit.getText()));
        }catch(Exception e){
          e.printStackTrace();
        }
      }
      @Override
      public void insertUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        update();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        update();
      }
    });
    
    timer = new Timer();
    timer.schedule(new TimerTask() {
      @Override
      public void run() {
        boardWatcher.doUpdate();
      }
    }, 0, 30);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    findBoardButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    keyDelay = new javax.swing.JTextField();
    towerGap = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    buildUpLimit = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    breakDownLimit = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    findBoardButton.setText("Find Board");
    findBoardButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findBoardButtonActionPerformed(evt);
      }
    });

    jLabel1.setText("Key Delay:");

    keyDelay.setText("50");

    towerGap.setText("2");

    jLabel2.setText("Tower Gap:");

    buildUpLimit.setText("15");

    jLabel3.setText("Buildup Limit:");

    breakDownLimit.setText("5");

    jLabel4.setText("Breakdown Limit:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(keyDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(findBoardButton)
              .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(towerGap, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buildUpLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
            .addComponent(breakDownLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(findBoardButton)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(keyDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(towerGap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(buildUpLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(breakDownLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void findBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBoardButtonActionPerformed
    EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        boardFrame.setOpacity(0.5f);
        boardFrame.setVisible(true);

      }
    });
    boardWatcher.setRun(false);
  }//GEN-LAST:event_findBoardButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    JFrame.setDefaultLookAndFeelDecorated(true);
    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TFrame().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField breakDownLimit;
  private javax.swing.JTextField buildUpLimit;
  private javax.swing.JButton findBoardButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField keyDelay;
  private javax.swing.JTextField towerGap;
  // End of variables declaration//GEN-END:variables
}
